
title: Ravi Tripathi
email: ravitripathi1996@gmail.com
description: Ravi Tripathi's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ravitripathi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rhotau
github_username:  ravitripathi

# Build settings
remote_theme: thelehhman/plainwhite-jekyll
plugins:
  - jekyll-feed

plainwhite:
  name: Ravi Tripathi
  tagline: Mobile App Developer
  date_format: "%b %-d, %Y"
  # style: black
  sitemap: true
  search: true
  show_excerpts: true
  disqus_shortname: ravitripathi
  # showPicker: true
  dark_mode: true
  # showNav: true
  
  # navigation:
  #   - title: My Work
  #     url: "/my-work"
  #   - title: Resume
  #     url: "/resume"

  social_links:
    twitter: rhotau
    github:  ravitripathi
    linkedIn: in/ravitripathi1996
