
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: texture
plugins:
  - jekyll-feed

texture:
  title: Ravi Tripathi
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: blue
  # showNav: true
  
  # navigation:
  #   - title: My Work
  #     url: "/my-work"
  #   - title: Resume
  #     url: "/resume"

  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman # format: locale/username